'use client';

/* eslint-disable @next/next/no-img-element -- Preview local website assets and uploaded originals without image optimization. */

import type { AdPageContent, AdPageImageKey } from '@/lib/ad-page-schema';

export default function AdPagePreview({ content: p }: { content: AdPageContent }) {
  const c = p.copy;
  const title = (text: string) => <h2 className="mb-5 text-2xl font-semibold leading-tight text-wareongo-blue">{text}</h2>;
  const cta = (text: string) => <span className="mt-4 inline-flex rounded-lg bg-wareongo-blue px-4 py-2 text-xs font-semibold text-white">{text} →</span>;
  const figures = (items: AdPageContent['overviewStats']) => <dl className="grid grid-cols-2 gap-3 lg:grid-cols-4">{items.map((item, i) => <div key={i} className="rounded-xl border border-wareongo-blue/15 bg-white p-4"><dt className="text-xs text-wareongo-slate">{item.label}</dt><dd className="mt-2 text-xl font-semibold">{item.value}</dd></div>)}</dl>;
  const photo = (key: AdPageImageKey) => p.images[key].url ? <img src={p.images[key].url} alt={p.images[key].alt} className="aspect-video w-full rounded-t-xl object-cover" /> : <div className="aspect-video rounded-t-xl bg-wareongo-blue/5" />;
  const imageCards = (prefix: string, buttonLabel?: string) => <div className="grid grid-cols-2 gap-3 lg:grid-cols-3">{(Object.keys(p.images) as AdPageImageKey[]).filter(key => key.startsWith(prefix)).map(key => <figure key={key} className="overflow-hidden rounded-xl border border-wareongo-blue/15 bg-white">{photo(key)}<figcaption className="p-3 text-xs leading-relaxed">{p.images[key].alt}{buttonLabel && <div>{cta(buttonLabel)}</div>}</figcaption></figure>)}</div>;
  return <section aria-label="Ad page content preview" className="space-y-12 overflow-hidden rounded-2xl border border-wareongo-blue/15 bg-wareongo-ivory p-5 text-wareongo-blue sm:p-8">
    {/* Local copies of the imported website photos and uploaded R2 images. */}
    <div className="grid gap-6 lg:grid-cols-[1.25fr_1fr]">
      <div><h1 className="text-3xl font-bold leading-tight">{c.heroHeading}<span className="block">{c.heroAccent}</span></h1><p className="mt-5 whitespace-pre-line text-sm leading-relaxed text-wareongo-slate">{c.heroIntro}</p><ul className="mt-4 list-disc space-y-2 pl-5 text-sm">{p.heroPoints.map((point, i) => <li key={i}><strong>{point.value}</strong> {point.label}</li>)}</ul></div>
      <div className="rounded-xl border border-wareongo-blue/20 bg-white p-5"><p className="cms-eyebrow">{c.enquiryEyebrow}</p><h2 className="mt-2 text-xl font-semibold">{c.enquiryHeading}</h2><p className="mt-2 text-sm text-wareongo-slate">{c.enquiryDescription}</p><div className="mt-4 space-y-3">{['Name', 'Company Name', 'Phone Number', 'Email (optional)'].map(label => <div key={label}><p className="mb-1 text-xs">{label}</p><div className="h-10 rounded-lg border border-wareongo-blue/20" /></div>)}</div>{cta(c.enquirySubmit)}</div>
    </div>
    <section>{title(c.featuredHeading)}{imageCards('featured-')}</section>
    <section><p className="cms-eyebrow mb-2">{c.availableEyebrow}</p>{title(c.availableHeading)}<div className="mb-4 flex flex-wrap gap-2">{[c.filterAll, c.filterSmall, c.filterMedium, c.filterLarge].map((text, i) => <span key={i} className="rounded-full border border-wareongo-blue/20 px-3 py-1 text-xs">{text}</span>)}</div><p className="mb-4 text-xs text-wareongo-slate">Photos across all size categories. The website shows six listings for the selected size.</p>{imageCards('warehouse-')}<p className="mt-4 text-sm text-wareongo-slate">{c.availableFooter.replaceAll('{listings}', 'all current listings')}</p>{cta(c.availableCta)}</section>
    <section>{title(c.locationsHeading)}{imageCards('micromarket-', c.locationsCta)}<p className="mt-4 text-xs text-wareongo-slate">{c.mapLabel} · {c.mapCaption}</p></section>
    <section>{title(c.areaHeading)}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">{c.areaNeedHeading}</th><th className="p-3">{c.areaLocationsHeading}</th></tr></thead><tbody>{p.areaRows.map((row, i) => <tr key={i} className="border-t border-wareongo-blue/15"><td className="p-3">{row.need}</td><td className="p-3">{row.areas.join(', ')}</td></tr>)}</tbody></table></div></section>
    <section>{title(c.whyHeading)}<div className="space-y-3">{p.benefits.map(item => <div key={item.id} className="rounded-xl border border-wareongo-blue/15 bg-white p-4"><h3 className="font-semibold">{item.title}</h3><p className="mt-2 whitespace-pre-line text-sm text-wareongo-slate">{item.body || 'Supporting copy'}</p></div>)}</div></section>
    <section className="rounded-xl bg-wareongo-blue p-6 text-center text-white"><h2 className="text-2xl font-semibold">{c.requestHeading}</h2><p className="mt-3 text-sm">{c.requestDescription}</p><p className="mt-2 text-xs">{c.requestDetails}</p><p className="mt-5 text-sm font-semibold">{c.requestCta} → · {c.requestPhoneCta}</p></section>
    <section>{title(c.servicesHeading)}<div className="grid gap-3 sm:grid-cols-2">{p.services.map(item => <div key={item.id} className="rounded-xl border border-wareongo-blue/15 bg-white p-5"><h3 className="font-semibold">{item.title}</h3><p className="mt-2 whitespace-pre-line text-sm leading-relaxed text-wareongo-slate">{item.body}</p>{cta(item.cta)}</div>)}</div><div className="mt-4 overflow-hidden rounded-xl">{photo('services')}</div></section>
    <section>{title(c.audiencesHeading)}<div className="grid gap-3 lg:grid-cols-3">{p.audiences.map(item => <div key={item.id} className="rounded-xl border border-wareongo-blue/15 bg-white p-5"><h3 className="font-semibold">{item.title}</h3><p className="mt-2 whitespace-pre-line text-sm leading-relaxed text-wareongo-slate">{item.body}</p>{cta(item.primaryCta)}{item.secondaryCta && <div>{cta(item.secondaryCta)}</div>}</div>)}</div></section>
    <section><p className="cms-eyebrow mb-2">{c.overviewEyebrow}</p>{title(c.overviewHeading)}<div className="mb-6 grid gap-5 lg:grid-cols-2">{p.overviewParagraphs.map((text, i) => <p key={i} className="whitespace-pre-line text-sm leading-relaxed text-wareongo-slate">{text}</p>)}</div>{figures(p.overviewStats)}</section>
    <section>{title(c.statsHeading)}<p className="text-sm text-wareongo-slate">The market tables use the current warehouse catalogue.</p></section>
  </section>;
}
